# test on staging:
group: dev

language: android
android:
  components:
#    - build-tools-21.1.1
#    - android-21
#    - android-19
    - android-14
    - android-16
#  licenses:
#    - 'android\-sdk\-license\-.*'
script:
  - cd application
  - android update project -p . --name Atomic --subprojects --target android-21
  - ant clean debug
